/**
 * Created by Hunter on 5/25/2016.
 */

var g_sounds = {
    chiabai:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/chiabai.wav":"res/sounds/mobile/chiabai.mp3",
    fire1:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/e_fire1.wav":"res/sounds/mobile/e_fire1.mp3",

    baobinh_12caydongmau:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/baobinh_12caydongmau.wav":"res/sounds/mobile/baobinh_12caydongmau.mp3",
    baobinh_12caydongmau:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/baobinh_12caydongmau.wav":"res/sounds/mobile/baobinh_12caydongmau.mp3",
    baobinh_13caydongmau:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/baobinh_13caydongmau.wav":"res/sounds/mobile/baobinh_13caydongmau.mp3",
    baobinh_3caisanh:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/baobinh_3caisanh.wav":"res/sounds/mobile/baobinh_3caisanh.mp3",
    baobinh_3caithung:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/baobinh_3caithung.wav":"res/sounds/mobile/baobinh_3caithung.mp3",
    baobinh_lucphebon:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/baobinh_lucphebon.wav":"res/sounds/mobile/baobinh_lucphebon.mp3",
    baobinh_sanhrong:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/baobinh_sanhrong.wav":"res/sounds/mobile/baobinh_sanhrong.mp3",
    batsapnay:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/batsapnay.wav":"res/sounds/mobile/batsapnay.mp3",
    BinhLung:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/BinhLung.wav":"res/sounds/mobile/BinhLung.mp3",
    chaomung_1:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/chaomung_1.wav":"res/sounds/mobile/chaomung_1.mp3",
    chaomung_2:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/chaomung_2.wav":"res/sounds/mobile/chaomung_2.mp3",
    e_OutCan:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/e_OutCan.wav":"res/sounds/mobile/e_OutCan.mp3",
    e_OutVol:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/e_OutVol.wav":"res/sounds/mobile/e_OutVol.mp3",
    finishgroupcard:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/finishgroupcard.wav":"res/sounds/mobile/finishgroupcard.mp3",
    MauBinh:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/MauBinh.wav":"res/sounds/mobile/MauBinh.mp3",
    maubinh_12caydongmau:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/maubinh_12caydongmau.wav":"res/sounds/mobile/maubinh_12caydongmau.mp3",
    maubinh_13caydongmau:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/maubinh_13caydongmau.wav":"res/sounds/mobile/maubinh_13caydongmau.mp3",
    maubinh_3caisanh:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/maubinh_3caisanh.wav":"res/sounds/mobile/maubinh_3caisanh.mp3",
    maubinh_3caithung:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/maubinh_3caithung.wav":"res/sounds/mobile/maubinh_3caithung.mp3",
    maubinh_lucphebon:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/maubinh_lucphebon.wav":"res/sounds/mobile/maubinh_lucphebon.mp3",
    maubinh_sanhrong:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/maubinh_sanhrong.wav":"res/sounds/mobile/maubinh_sanhrong.mp3",
    rematch_1:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/rematch_1.wav":"res/sounds/mobile/rematch_1.mp3",
    rematch_2:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/rematch_2.wav":"res/sounds/mobile/rematch_2.mp3",
    rematch_3:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/rematch_3.wav":"res/sounds/mobile/rematch_3.mp3",
    saproi:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/saproi.wav":"res/sounds/mobile/saproi.mp3",
    sobai_00:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/sobai_00.wav":"res/sounds/mobile/sobai_00.mp3",
    start_1:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/start_1.wav":"res/sounds/mobile/start_1.mp3",
    s_lose:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/s_lose.wav":"res/sounds/mobile/s_lose.mp3",
    s_win:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/s_win.wav":"res/sounds/mobile/s_win.mp3",
    Thang:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/Thang.wav":"res/sounds/mobile/Thang.mp3",
    thang_culu:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_culu.wav":"res/sounds/mobile/thang_culu.mp3",
    thang_doi:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_doi.wav":"res/sounds/mobile/thang_doi.mp3",
    thang_mauthau:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_mauthau.wav":"res/sounds/mobile/thang_mauthau.mp3",
    thang_samchicuoi:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_samchicuoi.wav":"res/sounds/mobile/thang_samchicuoi.mp3",
    thang_sanh:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_sanh.wav":"res/sounds/mobile/thang_sanh.mp3",
    thang_thu:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_thu.wav":"res/sounds/mobile/thang_thu.mp3",
    thang_thung:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_thung.wav":"res/sounds/mobile/thang_thung.mp3",
    thang_thungphasanh:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_thungphasanh.wav":"res/sounds/mobile/thang_thungphasanh.mp3",
    thang_tuquy:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/thang_tuquy.wav":"res/sounds/mobile/thang_tuquy.mp3",
    Thua:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/Thua.wav":"res/sounds/mobile/Thua.mp3",
    win_1:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/win_1.wav":"res/sounds/mobile/win_1.mp3",
    win_2:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/win_2.wav":"res/sounds/mobile/win_2.mp3",
    win_3:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/win_3.wav":"res/sounds/mobile/win_3.mp3",
    xepbai_culu:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_culu.wav":"res/sounds/mobile/xepbai_culu.mp3",
    xepbai_doi:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_doi.wav":"res/sounds/mobile/xepbai_doi.mp3",
    xepbai_mauthau:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_mauthau.wav":"res/sounds/mobile/xepbai_mauthau.mp3",
    xepbai_samchi:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_samchi.wav":"res/sounds/mobile/xepbai_samchi.mp3",
    xepbai_sanh:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_sanh.wav":"res/sounds/mobile/xepbai_sanh.mp3",
    xepbai_thu:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_thu.wav":"res/sounds/mobile/xepbai_thu.mp3",
    xepbai_thung:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_thung.wav":"res/sounds/mobile/xepbai_thung.mp3",
    xepbai_thungphasanh:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_thungphasanh.wav":"res/sounds/mobile/xepbai_thungphasanh.mp3",
    xepbai_tuquy:cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT?"res/sounds/wav/xepbai_tuquy.wav":"res/sounds/mobile/xepbai_tuquy.mp3"
};

var game_animations = [
    {folderpath:"res/Armatures/jackpot/",skeleton:"skeleton.xml",texture:"texture.plist",key:"jackpot"},
    {folderpath:"res/Armatures/Bacaisanh/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Bacaisanh"},
    {folderpath:"res/Armatures/BtnVang/",skeleton:"skeleton.xml",texture:"texture.plist",key:"BT_Vang"},
    {folderpath:"res/Armatures/BtnXanh/",skeleton:"skeleton.xml",texture:"texture.plist",key:"BT_xanh"},
    {folderpath:"res/Armatures/13quandongmau/",skeleton:"skeleton.xml",texture:"texture.plist",key:"13quandongmau"},
    {folderpath:"res/Armatures/Lucphebon/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Lucphebon"},
    {folderpath:"res/Armatures/Sanhrong/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Sanhrong"},
    {folderpath:"res/Armatures/Bacaithung/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Bacaithung"},
    {folderpath:"res/Armatures/batsaplang/",skeleton:"skeleton.xml",texture:"texture.plist",key:"batsaplang"},
    {folderpath:"res/Armatures/Maubinh/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Maubinh"},
    {folderpath:"res/Armatures/Baomaubinh/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Baomaubinh"},
    {folderpath:"res/Armatures/Hand_tut/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Hand_tut"},
    {folderpath:"res/Armatures/Bt_xepxong/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Bt_xepxong"},
    {folderpath:"res/Armatures/BtnHuyBo/",skeleton:"skeleton.xml",texture:"texture.plist",key:"Bt_huybo"},
    {folderpath:"res/Armatures/XepBai/",skeleton:"skeleton.xml",texture:"texture.plist",key:"FX_xepbaimaubinh"}
];
