// cmd id
var BO_CMD_EVENT_NOTIFY = 15251;
var BO_CMD_NOTIFY_ACTION = 15252;
var BO_CMD_OPEN_EVENT = 15253;
var BO_CMD_ACCUMULATE_INFO = 15254;
var BO_CMD_ROLL_EVENT = 15255;
var BO_CMD_ROLL_CHOOSE_DIRECT = 15256;
var BO_CMD_CHANGE_STAGE = 15807;
var BO_CMD_CHANGE_AWARD = 15257;
var BO_CMD_USER_CHANGE_AWARD_SUCCESS = 15258;
var BO_CMD_EVENT_TICKET_FROM_GOLD = 15259;
var BO_CMD_EVENT_BUY_TICKET_BY_G = 15830;
var BO_CMD_EVENT_SHOP_BONUS = 15260;
var BO_CMD_GET_REGISTER_INFORMATION = 15819;
var BO_CMD_GET_ROLL_HISTORY = 15261;
var BO_CMD_GET_GIFT_HISTORY = 15824;
var BO_CMD_CHANGE_PIECE= 15262;
var BO_CMD_EVENT_END = 15263;

var BO_CMD_GET_LAMP_INFO = 15820;
var BO_CMD_CHANGE_LAMP = 15821;
var BO_CMD_USE_LAMP = 15826;
var BO_CMD_SEND_LAMP = 15822;
var BO_CMD_IN_GAME_LAMP = 15828;

var BO_CMD_CHEAT_G_SERVER = 15264;
var BO_CMD_CHEAT_COIN_ACCUMULATE = 15265;
var BO_CMD_CHEAT_RESET = 15266;
var BO_CMD_CHEAT_COIN_FREE_DAY = 15813;
var BO_CMD_CHEAT_ITEM = 15267;
var BO_CMD_CHEAT_NUM_ROCK = 15268;
var BO_CMD_CHEAT_POS = 15269;
var BO_CMD_OPEN_CHEST = 15270;

// var BO_CMD_EVENT_NOTIFY = 15851;
// var BO_CMD_NOTIFY_ACTION = 15852;
// var BO_CMD_OPEN_EVENT = 15853;
// var BO_CMD_ACCUMULATE_INFO = 15854;
// var BO_CMD_EVENT_SHOP_BONUS = 15856;
// var BO_CMD_ROLL_EVENT = 15857;
// var BO_CMD_CHANGE_AWARD = 15858;
// var BO_CMD_USER_CHANGE_AWARD_SUCCESS = 15859;
// var BO_CMD_KEYCOIN_BONUS = 15861;
// var BO_CMD_CHEAT_ITEM = 15862;
// var BO_CMD_CHEAT_COIN_FREE_DAY = 15863;
// var BO_CMD_CHEAT_COIN_ACCUMULATE = 15864;
// var BO_CMD_CHEAT_G_SERVER = 15865;
// var BO_CMD_CHEAT_BREAK_DIRECT = 15866;
// var BO_CMD_CHEAT_RESET = 15867;
// var BO_CMD_NOT_IN_EVENT = 15868;

// var
var BO_WEEK_START = 1;
var BO_WEEK_END = 1;

var BO_ITEM_STORED = 999;
var BO_ITEM_OUT_GAME = 999999;
var BO_ITEM_LAMP = 9999;

var BO_MAX_ITEM_CONVERT_GIFT = 3;

var BO_NUM_ROLL_TYPE = 3;  // 1 - 10 - 100
var BO_MAX_FRIEND = 5;
var BO_ROW = 6;
var BO_COL = 12;
var BO_NUM_PIECE = 4;

var BO_MOVE_DIRECT = [
    [-1,0],[0,1],[1,0],[0,-1]
];// UP - RIGHT - DOWN - LEFT

var BO_UP = 0;
var BO_DOWN = 2;
var BO_RIGHT = 1;
var BO_LEFT = 3;

var BO_SPECIAL_POINT = [0, 3];

var BO_MOVE_SPLIT_VERTICAL = 3; // nhung hang lon hon hang 3 thi chi duoc di qua trai
var BO_MOVE_SPLIT_HORIZONTAL = 3; // nhung cot o ben trai thi chi di thang, nhung cot o ben phai thi chi di xuong

var BO_PIECE_IMAGE_SIZE = 115;
var BO_PIECE_MAX_ROW = 5;

var BO_CELL_ITEM = 100;
var BO_CELL_GOLD = -1;
var BO_CELL_ROCK = -2;
var BO_CELL_WATER = -3;
var BO_CELL_CHEST = -4;
var BO_CELL_MAP = -5;
var BO_CELL_MAP_BUBBLE = -6;
var BO_CELL_EMPTY = 0;

var BO_CELL_GOLD_SCALE = 0.4;

var BO_CELL_EFFECT_COUNT_DOWN = 3;

var BO_STONE_MAX_CHANGE = 5;

// character effect
var BO_TIME_MOVE_IN_CELL = 0.25;
var BO_CHARACTER_EXTREME_RUN = 3000;
var BO_CHARACTER_NUMBER_EXTREME_RUN = 1;
var BO_CHARACTER_PATH_EXTREME_RUN = 10;
var BO_CHARACTER_SPEED_EXTREME_RUN = 0.25;

var BO_BUBBLE_TIME_EXTREME_RUN = 10;
var BO_CHARACTER_SHADOW_RATIO = 15;

var BO_MAX_TIME_BUBBLE_IN_MAP = 5;
var BO_TIME_BUBBLE_RESULT_ROLL = 10;

var BO_TIME_CHANGE_MAP = 2;
var BO_BUBBLE_CHANGE_MAP = 50;
var BO_BUBBLE_RESULT_ROLL = 100;

// roll dice
var BO_ROLL_EXTRA_LIMIT = 10;
var BO_GOLD_GIFT_EXTRA_ID = 88;
var BO_DIAMOND_GIFT_EXTRA_ID = 89;
var BO_EXP_GIFT_EXTRA_ID = 90;
var BO_ROLL_DICE_TIME = 10;
var BO_UP_DICE_MOVE = 0.5;
var BO_PLATE_DICE_CHANGE_DIRECT = 0.05;
var BO_PLATE_DICE_MOVE = 0.025;

// GUI
var BO_GUI_BTN_CLOSE = 0;
var BO_GUI_NOTIFY_BTN_JOIN = 1;

var BO_MAP_ITEM_ZODER = 9999;
var BO_MAP_MOVE_ZODER = 999;

// button main scene
var BO_SCENE_BTN_STAGE_UP     = 10001;
var BO_SCENE_BTN_STAGE        = 10000;

var BO_SCENE_BTN_ROLL_ONCE        = 100;
var BO_SCENE_BTN_ROLL_TEN         = 101;
var BO_SCENE_BTN_ROLL_HUNDRED     = 102;

var BO_SCENE_CHEAT_G_SERVER       = 501;
var BO_SCENE_CHEAT_RESET_SERVER       = 502;
var BO_SCENE_CHEAT_ITEM = 503;
var BO_SCENE_CHEAT_SHOW_FULLTIME = 504;
var BO_SCENE_CHEAT_EXP_COIN = 505;
var BO_SCENE_CHEAT_COIN_FREE = 506;
var BO_SCENE_CHEAT_NUM_ROLL = 507;
var BO_SCENE_CHEAT_ROCK = 508;
var BO_SCENE_CHEAT_MAP = 509;
var BO_SCENE_CHEAT_POS = 510;
var BO_SCENE_CHEAT_CONVERT = 511;

var BO_SCENE_CHEAT_PIE_1 = 531;
var BO_SCENE_CHEAT_PIE_2 = 532;
var BO_SCENE_CHEAT_PIE_3 = 533;
var BO_SCENE_CHEAT_PIE_4 = 534;

var BO_SCENE_BTN_STAGE_DOWN       = 9999;

var BO_SCENE_BTN_HISTORY          = 11001;
var BO_SCENE_BTN_CLOSE          = 11002;
var BO_SCENE_BTN_HELP          = 11003;
var BO_SCENE_BTN_CHEAT          = 11004;
var BO_SCENE_BTN_SOUND          = 11005;
var BO_SCENE_BTN_NEWS          = 11006;
var BO_SCENE_BTN_SHOP          = 11007;
var BO_SCENE_BTN_PLAY          = 11008;
var BO_SCENE_BTN_OK          = 11009;
var BO_SCENE_BTN_LAMP         = 11012;
var BO_SCENE_BTN_OPEN_EVENT          = 11035;

var BO_SCENE_BTN_FANPAGE         = 11200;

var BO_SCENE_BTN_CHANGE     = 150;

var BO_PANEL_CHANGE = 40001;
var BO_PANEL_DESELECT = 40002;
var BO_PANEL_SELECT_ALL = 40003;

var BO_SCENE_TAB_HISTORY      = 1;
var BO_SCENE_TAB_GIFT      = 2;
var BO_SCENE_TAB_INFORMATION      = 3;
var BO_SCENE_TAB_CHANGE      = 4;
var BO_SCENE_TAB_LAMP      = 5;
var BO_SCENE_BTN_CHANGE_LAMP = 6;

var BO_HELP_NUM_PAGE = 6;
var BO_SHOW_LIST_ITEM_FULL = 1;
var BO_SHOW_LIST_ITEM_MINI = 0;

BO_ACCUMULATE_TIME_PROGRESS = 1;
BO_ACCUMULATE_TIME_MOVE = 0.5;
BO_ACCUMULATE_TIME_DELTA = 0.05;

var BO_TF_NAME = 1;
var BO_TF_ADDRESS = 2;
var BO_TF_PHONE = 3;
var BO_TF_CMND = 4;
var BO_TF_EMAIL = 5;

var BO_LAMP_IN_GAME_TAG = 100;

var BO_SCENE_DELAY_LOADING = 500;
var BO_CONFIG_TYPE_LAMP = [0, 9, 13];

// class
var BO_SCENE_CLASS = "BlueOceanScene";
var BO_RESULT_GUI_CLASS = "BlueOceanOpenResultGUI";
var BO_OPEN_GIFT_GUI_CLASS = "BlueOceanOpenGiftGUI";
var BO_REGISTER_GUI_CLASS = "BlueOceanRegisterInformationGUI";
var BO_ACCUMULATE_GUI_CLASS = "BlueOceanAccumulateGUI";
var BO_HELP_GUI_CLASS = "BlueOceanHelpGUI";
var BO_HISTORY_GUI_CLASS = "BlueOceanHistoryGUI";
var BO_CHANGE_LAMP_GUI_CLASS = "BlueOceanChangeLampGUI";
var BO_PIECE_GUI_CLASS = "BlueOceanPieceConvertGUI";
var BO_NOTIFY_CLASS = "BlueOceanEventNotifyGUI";
var BO_CHANGE_ITEM_CLASS = "BlueOceanPanelChangeItem";

var BO_NOTIFY_PROMOTE_G_CLASS = "BlueOceanNapGNotifyGUI";
var BO_NOTIFY_BONUS_G_CLASS = "BlueOceanBonusGNotifyPanel";
var BO_NOTIFY_BONUS_TICKET_CLASS = "BlueOceanBonusTicketDialog";
var BO_HAMMER_EMPTY_CLASS = "BlueOceanHammerEmptyDialog";

var BO_HAMMER_ROLL_EMPTY = 0;
var BO_HAMMER_NOTIFY_EMPTY = 1;
var BO_HAMMER_TICKET = 2;

var BO_NOTIFY_ORDER = 206;
var BO_NOTIFY_PROMOTE_G_ORDER = 206;
var BO_PIECE_GUI_ORDER = 207;
var BO_RESULT_GUI_ORDER = 201;
var BO_OPEN_GIFT_GUI_ORDER = 202;
var BO_REGISTER_GUI_ORDER = 205;
var BO_ACCUMULATE_GUI_ORDER = 200;
var BO_HELP_GUI_ORDER = 203;
var BO_HISTORY_GUI_ORDER = 203;
var BO_DIALOG_ORDER = 208;
var BO_NOTIFY_BONUS_G_ORDER = 209;

// Notify EventMgr
var BO_HAMMER_EMPTY_COUNT_DOWN_SHOW = 2;

var BO_BUBBLE_EFFECT_COUNT_DOWN = 5;

var BO_NOTIFY_BONUS_G_COUNT_DOWN = 300000;    // 5p

// image
var BO_IMAGE_CELL_MOVE = "res/Event/BlueOcean/BlueOceanUI/cell_move.png";
var BO_IMAGE_CHARACTER_SHADOW = "res/Event/BlueOcean/BlueOceanUI/mascotZP.png";
var BO_IMAGE_CHARACTER_SHADOW_LIGHT = "res/Event/BlueOcean/BlueOceanUI/shadow_mascot.png";
var BO_IMAGE_BUBBLE = "res/Event/BlueOcean/BlueOceanUI/bubble.png";
var BO_IMAGE_CELL_NORMAL = "res/Event/BlueOcean/BlueOceanUI/cell_normal.png";
var BO_IMAGE_STONE_REMAIN = "res/Event/BlueOcean/BlueOceanUI/stone_remain_move.png";
var BO_IMAGE_STONE = "res/EventMgr/BlueOcean/BlueOceanUI/cell_stone.png";
var BO_IMAGE_BG_GIFT = "res/EventMgr/BlueOcean/BlueOceanUI/cell_gift.png";
var BO_IMAGE_CELL_NORMAL_LEVEL = "res/EventMgr/BlueOcean/BlueOceanUI/cell_normal";
var BO_IMAGE_BG_GIFT_LEVEL = "res/EventMgr/BlueOcean/BlueOceanUI/cell_gift";
var BO_IMAGE_STONE_LEVEL = "res/EventMgr/BlueOcean/BlueOceanUI/stone";
var BO_IMAGE_BUTTON_IN_GAME = "res/Event/BlueOcean/BlueOceanUI/btnEventInGame.png";

// Type Item
var BO_ITEM_IN_MAIN_SCENE = 0;
var BO_ITEM_IN_CHANGE_SCENE = 1;

var BO_NUM_LEVEL = 3;